import geopandas as gpd
from a2a_framework.a2a.Artifact import Artifact
import joblib
import os
import traceback
from a2a_framework.a2a.Tool import ToolResult
import logging
from a2a_framework.utils.static import *
from a2a_framework.a2a.Messages import Messages
from a2a_framework.a2a.AgentState import AgentState
from a2a_framework.skills.Skill import Skill
import os


''' Default place for adding tool. From OSM to other useful tools'''

def send_message(**kwargs):

    from a2a_framework.utils.registry import registry
    
    '''This function will be a tool agents will have to communicate with each other. The messages they give will be converted to tasks
    args:
        1. target : The agent messages are targetted to
        2. task_description : What is required of the agent

        The rest of the inputs can be provided manually by the code
    output:
        The updated task
    '''
    
    target = kwargs["target"]
    task_description = kwargs["task_description"]
    conversation_id = kwargs["conversation_id"]
    logger = kwargs["logger_path"]
    session_id = kwargs["session_id"]
    filter_messages = kwargs.get("filter_messages","null")
    logger = logging.getLogger(logger)
    use_conversation_or_state = kwargs.get("use_conversation_or_state","conversation")

    
    

    if use_conversation_or_state == "conversation":
        logger.info(f"Sending message to agent {target} with task description {task_description} and conversation_id {conversation_id} and parent_id {kwargs['parent_id']}")
        logger.info(f"Filter messages is {filter_messages}")
        conversation = Messages.load(conversation_id,logger_path=kwargs["logger_path"])
    else:
        logger.info(f"Generating reply for agent {target} with updated state {target} and parent_id {kwargs['parent_id']}")
        conversation = AgentState.load_state(target, session_id, logger_path=kwargs["logger_path"])
        logger.info(f"showing messages of {target} and perspective {session_id} :  {conversation}" )

    
    # Need to handle human agent separately because human needs host agent and host agent needs human
    conversation_id = kwargs["conversation_id"]
    parent_id = kwargs["parent_id"]
    agent = registry[target]
    

    additional_tools = get_additional_skill_tools_for_agent(f"skill_tools_{target}_{session_id}")

    if additional_tools and len(additional_tools) > 0:
        logger.info(f"Additional skill tools loaded {additional_tools}")
        additional_tool_defs = [registry.get(i) for i in additional_tools]
        agent.tool_definitions = agent.tool_definitions + additional_tool_defs


    output = agent.run_agent(conversation.render_for(target, filter_messages=filter_messages) if hasattr(conversation,"render_for") else conversation.messages,session_id,parent_id)
    return ToolResult(output,[])
    

def code_executor(**kwargs):

    '''function to execute code generated by the llm
     args:
        1. code : The code to execute
        2. artifact_names : The names of the artifacts to provide as input
        3. data : A list of artifacts available to the agent if the agent is not provided with raw data then it will search the aritfacts folder
        output:
        The output of the code execution'''
    
    code = kwargs["code"]
    artifact_names = kwargs["artifact_names"]
    data = kwargs.get("data",None)
    data = [i.data for i in data if i.name in artifact_names] if data is not None else [joblib.load(os.path.join(ARTIFACT_PATH,f"{name}.pkl")).data for name in artifact_names if name+".pkl" in os.listdir(ARTIFACT_PATH)]
    logger = logging.getLogger(kwargs["logger_path"])
    try:
        namespace = {}
        code = "import matplotlib\nmatplotlib.use('Agg')\n" + code
        logger.info(f"Executing code {code}")
        exec(code,namespace)
        function_name = [name for name in namespace if callable(namespace[name])][-1]
        logger.info(f"function name {function_name}")
        output = namespace[function_name](data=data)
        logger.info("Output completed")
        # We are assuming that the output of the coding agent will be  a list of 4 things [summary of output, artifact name, artifact description, artifact data ], None if no artifact
        if isinstance(output,list):
        
            # if a valid artifact is returned we will save it to the artifacts folder so that it can be used later
            if output[1] is not None and output[2] is not None and output[3] is not None:
                artifact = Artifact(name=output[1],description=output[2],data=output[3])
                if isinstance(output[3], (gpd.GeoDataFrame, gpd.GeoSeries)):
                    if not output[3].empty:
                        joblib.dump(artifact, os.path.join(ARTIFACT_PATH,f"{artifact.name}.pkl"))
                        return ToolResult(output=output[0], artifacts=[Artifact(name=output[1],description=output[2],data=output[3])])
                    else:
                        return ToolResult(output="The search return no results and no artifacts are generated",artifacts=[])
                else:
                    joblib.dump(artifact, os.path.join(ARTIFACT_PATH,f"{artifact.name}.pkl"))
                    return ToolResult(output=output[0], artifacts=[Artifact(name=output[1],description=output[2],data=output[3])])
            else:
                return ToolResult(output=output[0],artifacts=[])
        else:
            return ToolResult(output=output,artifacts=[])
    except Exception as e:
        logger.error("ERROR EXECUTING CODE",exc_info=True)
        return ToolResult(output=traceback.format_exc(),artifacts=None)


def set_additional_skill_tools_for_agents(key:str, addtional_tools:list):
    from a2a_framework.a2a.redis_client import redis_client

    with redis_client.pipeline() as pipe:
        pipe.multi()
        pipe.delete(key)
        if addtional_tools and len(addtional_tools) > 0:
            pipe.rpush(key,*addtional_tools)
        pipe.execute()

def get_additional_skill_tools_for_agent(key):
    from a2a_framework.a2a.redis_client import redis_client
    return redis_client.lrange(key,0,-1)

def load_skill(**kwargs):
    '''Function to load a skill from the available skills folder
    args:
        1. skill_name : The name of the skill to load
    output:
        The skill object in a readable format for the agent to use. The skill object will contain the skill name, description and usage
    '''

    skill_name = kwargs["skill_name"]
    requesting_agent = kwargs["source"]
    session_id = kwargs["session_id"]
    logger = logging.getLogger(kwargs["logger_path"])
    registered_skills = Skill.get_all_registered_skills()
    skill = next((s for s in registered_skills if s.skill_name == skill_name), None)
    skill_tools = [tool for tool in skill.skill_tools] if len(skill.skill_tools) > 0 else []
    
    if skill is None:
        raise ValueError(f"Skill {skill_name} not found in available skills")
    else:
        logger.info(f"Modifying tool definitions of {requesting_agent} with {skill_tools}")
        set_additional_skill_tools_for_agents(f"skill_tools_{requesting_agent}_{session_id}",skill_tools)
        
        return ToolResult(output=f"""Loaded skill {skill.skill_name} \n 
        Note : Any previous tools are now removed. Do not attempt to use information from previous skills \n
               Description : {skill.skill_description} \n
               available tools : {skill.skill_tools} \n
               Usage Details : {skill.skill_usage_details}""", artifacts=[])
    



