class Artifact():
    def __init__(self, name:str, description:str, data:object ):
        '''
        A simple wrapper class to wrap any data objects. These will be later stored in the artifacts folders as objects.
        1. name : Artifact name
        2. description : A detailed description for the agent's better understanding of what is the data and how was it extracted. Generated by the agent itself.
        3. data : The actual data object. Can be anything as long as it can be loaded in python
        '''
        self.name = name
        self.description = description
        self.data = data