from enum import Enum
import json
from a2a_framework.a2a.redis_client import redis_client
from pydantic import BaseModel
from dataclasses import asdict,dataclass
import logging

class RouterStatus(str,Enum):
    RUNNING = "RUNNING"
    END = "END"

@dataclass
class RouterOutput:
    '''
    This is an example class of type RouterOutput. It contains each corresponding output of the 
    router which is generated as an agent executes a particular route. This is made because 
    users may want to use the router outputs to process a query or route to other agents.
    args:
    1. route_output_id : str = A unique id for the the router
    2. agent_name : str = A name of the agent which has generated the output.
    3. schema : dict = A json schema if generated by the agent
    4. logger_path : str = A path containing the logger 
    5. raw_output : str = The agent output
    '''

    route_output_id : str
    agent_name : str
    output : str
    schema : dict
    logger_path : str
    raw_output : str
    artifacts : list

    def __init__(self, route_output_id, agent_name:str, output:str, raw_output:str, logger_path:str, artifacts ,schema:object={}):

        self.logger_path = str(logger_path)
        logger = logging.getLogger(logger_path)
        logger.info(f"Received schema in router output {schema}, and type {type(schema)} and instance {isinstance(schema,BaseModel)}")
        self.route_output_id = route_output_id
        self.agent_name = agent_name
        self.output = output
        self.artifacts = artifacts
        if isinstance(schema,BaseModel):
            self.schema = json.loads(schema.model_dump_json())
        elif isinstance(schema,dict):
            self.schema = schema
        else:
            schema = {}
        self.raw_output = raw_output

    def save(self):
        '''This is the save function of router routput. 
        It saves the router output and also adds the output to the router pool
        The router pool is used for outputs to be accessible and persistent accross
        workers.'''
        data = asdict(self)
        data["schema"] = json.dumps(self.schema)
        data["artifacts"] = json.dumps(self.artifacts)
        redis_client.hset(f"Router_output:{self.route_output_id}", mapping=data)
        redis_client.rpush(f"Router_output_pool",json.dumps(data))

    @classmethod
    def load(cls, id):
        '''This is the load function for the router output. It is very same as other load
        functions'''
        data =  redis_client.hgetall(f"Router_output:{id}")
        route_output = cls(
            route_output_id = id,
            agent_name = data["agent_name"],
            output = data["output"],
            logger_path = data["logger_path"],
            schema = json.loads(data["schema"]),
            raw_output = data["raw_output"],
            artifacts = json.loads(data["artifacts"])
        )
        return route_output

    @classmethod
    def load_all(cls):
        '''Similar to load but loads all the  in order of creating'''
        data_all = redis_client.lrange("Router_output_pool",0,-1)
        if len(data_all) == 0:
            return []
        data_all = [json.loads(data) for data in data_all]
        outputs = [cls(
            route_output_id = data["route_output_id"],
            agent_name = data["agent_name"],
            output = data["output"],
            logger_path = data["logger_path"],
            schema = json.loads(data["schema"]),
            raw_output = data["raw_output"],
            artifacts = json.loads(data["artifacts"])
        ) for data in data_all]
        return outputs


